name: Lint

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkoout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --fronzen-lockfile

      - name: Run Prettier
        run: bun run format:check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkoout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --fronzen-lockfile

      - name: Run ESLint
        run: bun run lint
